#cloud-config
package_update: true
package_upgrade: true

packages:
  - apache2
  - libapache2-mod-php
  - mysql-server
  - php
  - php-mysql
  - php-curl
  - php-gd
  - php-mbstring
  - php-xml
  - php-soap
  - php-intl
  - php-zip
  - unzip
  - wget

runcmd:
  # Start and enable services
  - systemctl enable --now apache2
  - systemctl enable --now mysql

  # Configure MySQL (no root password needed; auth_socket works on Ubuntu)
  - mysql -e "CREATE DATABASE IF NOT EXISTS ${db_name};"
  - mysql -e "CREATE USER IF NOT EXISTS '${db_user}'@'localhost' IDENTIFIED BY '${db_password}';"
  - mysql -e "GRANT ALL PRIVILEGES ON ${db_name}.* TO '${db_user}'@'localhost';"
  - mysql -e "FLUSH PRIVILEGES;"

  # Remove default Apache page
  - rm -rf /var/www/html/*

  # Download and configure WordPress
  - wget -O /tmp/wordpress.tar.gz https://wordpress.org/latest.tar.gz
  - tar -xzf /tmp/wordpress.tar.gz -C /tmp
  - cp -R /tmp/wordpress/* /var/www/html/
  - rm -rf /tmp/wordpress /tmp/wordpress.tar.gz

  # Configure wp-config.php
  - cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
  - sed -i "s/database_name_here/${db_name}/" /var/www/html/wp-config.php
  - sed -i "s/username_here/${db_user}/" /var/www/html/wp-config.php
  - sed -i "s/password_here/${db_password}/" /var/www/html/wp-config.php

  # Permissions
  - chown -R www-data:www-data /var/www/html/
  - find /var/www/html/ -type d -exec chmod 755 {} \;
  - find /var/www/html/ -type f -exec chmod 644 {} \;

  # Restart Apache
  - systemctl restart apache2
